RATEPLUG-19: add support for zero percent installment
ratepay/php-library pull request #2
Opened 2019-10-15 16:56 UTC by rommelfreddy

2020-01-02 14:31 UTC, eiriarte-mendez requested changes
Please check the comments at src/Model/Response/ConfigurationRequest.php .
Otherwise we are not able to merge this change request.

2020-01-02 14:31 UTC, eiriarte-mendez commented on src/Model/Response/ConfigurationRequest.php
> +                    $rateAmount = $orderAmount / $interestRateMonth;
Hi @rommelfreddy,

this line seems dangerous... it is an unsafe division by zero, since `$insterestRateMonth` its lower than `$interestRate` it is a high risk to perform this operation.

Could you please tell us which values are you expecting from the method when using zero-percent financing?

2020-01-06 07:48 UTC, rommelfreddy commented on src/Model/Response/ConfigurationRequest.php
> +                    $rateAmount = $orderAmount / $interestRateMonth;
yeah. You are right!
I used the wrong variable. 
i fixed that.

2020-02-24 08:26 UTC, eiriarte-mendez approved these changes
Seems to be OK now

2020-02-24 08:27 UTC, merged