M1-34: Update docblock headers
ratepay/php-library pull request #26
Opened 2022-02-22 10:44 UTC by BoulangerV

2022-03-18 14:30 UTC, hamail-tahir commented
The title of PR says  Update docblock headers , but why is this update done? and was this text approved?

2022-03-18 14:36 UTC, MartinKuhl commented
> The title of PR says Update docblock headers , but why is this update done? and was this text approved?

This task was done to shorten the legal blocks and to synchronize the legal block between the php-lib and our shop moduls.
Each legal block is now referencing to the LICENSE file with the full MIT license information.

2022-03-28 08:37 UTC, eiriarte-mendez requested changes
@MartinKuhl , @BoulangerV all checks are failing, can you please check and fix that first?

2022-05-06 12:30 UTC, eiriarte-mendez approved these changes

2022-05-06 12:31 UTC, merged