Support for german locale on negative amounts
ratepay/php-library pull request #4
Opened 2020-01-31 17:56 UTC by KevinHansen23

Currently if locale is set to de_DE negative Amounts are formatted with `,` instead of `.`. That leads to a NumberFormatException, which is fixed with these changes.

2020-02-18 04:49 UTC, KevinHansen23 commented
Hi @eiriarte-mendez,

any Updates on this?

Kind regards
Kevin Hansen

2020-02-24 08:15 UTC, eiriarte-mendez commented
Hi @KevinHansen23, 

Thanks for the PR. Could you please add an explanation why this library should support other number formats? Our Gateway at RatePAY accepts only the english format at the moment...

2020-02-24 08:16 UTC, eiriarte-mendez reviewed
Could you please update your PR to the latest master, so test can be executed

2020-02-25 03:14 UTC, KevinHansen23 commented
Hi @eiriarte-mendez,

our CRM is set to `(LC_ALL,"de_DE.utf8");`.

The problem now is, that the library only accepts the english number format but uses `floatval();` which formats numbers based on the current locale. So even if we push a value with the correct format (e.g. `5.95`), the library calls `changeValueToNegative` and the value is changed to `-5,95`.

There is no way to fix this without these changes because the malformatting happens within the library.
In the `changeAmountToFloat` function you addressed this problem, but not within the `changeValueToNegative` function.

Regarding the Update:
I didn't find a way to update my fork with an open PR (I'm using Github in browser only).

Kind regards
Kevin

2020-09-11 06:22 UTC, eiriarte-mendez requested changes
PR is not passing checks

2020-09-11 06:44 UTC, MartinKuhl commented
> PR is not passing checks

what has to be adjust?

2020-09-11 07:10 UTC, eiriarte-mendez reviewed
only style checks...

2020-09-11 07:10 UTC, eiriarte-mendez commented on src/Service/Util.php
> +     * Changes value to negative if necessary
```suggestion
     * Changes value to negative if necessary.
```

2020-09-11 07:10 UTC, eiriarte-mendez commented on src/Service/Util.php
> +     * Changes the camel case notation to separation by underscore
```suggestion
     * Changes the camel case notation to separation by underscore.
```

2020-09-11 07:10 UTC, eiriarte-mendez commented on src/Service/Util.php
> +        $value = number_format($value, 2, ".", "");
```suggestion
        $value = number_format($value, 2, '.', '');
```

2020-09-11 07:10 UTC, eiriarte-mendez commented on src/Service/Util.php
>       * @return string
```suggestion
     *
     * @return string
```

2020-09-11 07:10 UTC, eiriarte-mendez commented on src/Service/Util.php
>       * @return string
```suggestion
     *
     * @return string
```

2020-09-11 07:10 UTC, eiriarte-mendez commented on src/Service/Util.php
> +        $value =  ($value > 0) ? $value * -1 : $value;
```suggestion
        $value = ($value > 0) ? $value * -1 : $value;
```

2023-08-04 13:15 UTC, closed without merging